#!/usr/bin/env python3
"""Measure what each backend does with each feature, and record it.

Run after adding a backend, adding a feature rule, or changing how a backend
handles one. A test regenerates and compares, so stale data is a build failure.
"""

import json
import logging
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

logging.disable(logging.CRITICAL)

from multigen.backends.registry import registry  # noqa: E402
from multigen.frontend.backend_capabilities import MATRIX_PATH, measure_backend  # noqa: E402


def build_matrix(existing: dict[str, dict[str, dict[str, str]]]) -> dict[str, object]:
    """Probe every available backend with every feature probe.

    Each cell records what the backend emitted and what happened when the
    emitted program was built and run against CPython's answer.

    A backend absent from this interpreter keeps its previously measured rows.
    The LLVM backend is not registered without llvmlite, which is excluded on
    Python 3.14, so regenerating there would otherwise delete its data.
    """
    available = set(registry.list_backends())
    backends: dict[str, dict[str, dict[str, str]]] = {}

    for backend_name in sorted(available | set(existing)):
        if backend_name not in available:
            sys.stderr.write(f"warning: {backend_name} backend unavailable here; keeping recorded rows\n")
            backends[backend_name] = {k: dict(v) for k, v in existing[backend_name].items()}
            continue
        sys.stderr.write(f"measuring {backend_name}...\n")
        backends[backend_name] = measure_backend(backend_name, existing.get(backend_name))

    return {
        "_comment": (
            "Generated by scripts/generate_capability_matrix.py. Do not edit by hand: "
            "run `make capabilities`."
        ),
        "backends": backends,
    }


def main() -> int:
    """Write the matrix, reporting whether anything changed."""
    existing_text = MATRIX_PATH.read_text(encoding="utf-8") if MATRIX_PATH.exists() else ""
    recorded = json.loads(existing_text)["backends"] if existing_text else {}
    payload = json.dumps(build_matrix(recorded), indent=2, sort_keys=True) + "\n"
    if existing_text == payload:
        sys.stdout.write("backend_capabilities.json is up to date\n")
        return 0
    MATRIX_PATH.write_text(payload, encoding="utf-8")
    sys.stdout.write("backend_capabilities.json regenerated\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
